resolver: lts-13.9

packages:
- .
- location:
    git: https://github.com/spell-music/csound-catalog
    commit: 4ac5a630efb1a0fac14fe726adbd0b5fc217da30
  extra-dep: True

extra-deps:
- csound-expression-5.3.2
- csound-expression-dynamic-0.3.3
- csound-expression-opcodes-0.0.4.0
- csound-expression-typed-0.2.2.0
- csound-sampler-0.0.9.0
- sharc-timbre-0.2
- temporal-media-0.6.3
- data-fix-cse-0.0.2
- wl-pprint-1.2.1


